version: '3'

services:
  db:
    image: postgres:10
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    ports:
    - 5432:5432
    expose:
    - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 6
  redis:
    image: redis:3.2.11
  magine:
    restart: always
    build: .
    volumes:
      - ./_state:/home/magine/_state
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db


  celery:
    build: .
    volumes:
    - '/home/magine'
    command: celery -A magine_gui_app worker --loglevel=info
    environment:
    - CELERY_BROKER=redis://redis:6379/0
    - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
    - redis
    - magine


volumes:
  postgres_data: