version: '3'
services:
  magine:
    build: .
    volumes:
      - ./_state/:/magine_home/_state/
    command: python3 manage.py makemigrations
    command: python3 manage.py migrate
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
