version: '3'
services:
  magine:
    build: .
    volumes:
      - ./_state/:/magine/_state/
    environment:
      - UWSGI_PROCESSES=3
      - UWSGI_MASTER=1
      - UWSGI_SOCKET=:8000
      - UWSGI_MODULE=magine_gui_app.wsgi
      - UWSGI_ENABLE_THREADS=1
      - UWSGI_UID=www-data
      - UWSGI_GID=www-data
    ports:
      - "8000:8000"
