# Generated by Django 2.2 on 2020-07-10 22:52

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0002_auto_20190115_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data',
            field=picklefield.fields.PickledObjectField(blank=True, compress=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='enrichmentoutput',
            name='significant',
            field=models.BooleanField(blank=True),
        ),
    ]
